exports.ids = [4];
exports.modules = {

/***/ "./src/client/components/property/modalGallery/desktop/index.js":
/*!**********************************************************************!*\
  !*** ./src/client/components/property/modalGallery/desktop/index.js ***!
  \**********************************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ \"react\");\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var prop_types__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! prop-types */ \"prop-types\");\n/* harmony import */ var prop_types__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(prop_types__WEBPACK_IMPORTED_MODULE_1__);\n/* harmony import */ var _styled__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./styled */ \"./src/client/components/property/modalGallery/desktop/styled.js\");\n\n\n\n\nvar DesktopImg = function DesktopImg(_ref) {\n  var gallery = _ref.gallery,\n      onOpenModalMulti = _ref.onOpenModalMulti;\n  var galleryLength = gallery[0].items.length;\n  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_styled__WEBPACK_IMPORTED_MODULE_2__[\"DesktopWrap\"], {\n    length: galleryLength\n  }, gallery[0].items.map(function (item, index) {\n    return (\n      /* index == 1 ?\n      <SmallWrap>\n        <ImgStyle\n          index={index}\n          src={item.gallery_image.url}\n          onClick={() => onOpenModalMulti(item.gallery_image.url, gallery[0].items)}\n          key={item.gallery_image.url}\n        />\n      </SmallWrap>\n      : */\n      react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_styled__WEBPACK_IMPORTED_MODULE_2__[\"ImgStyle\"], {\n        index: index,\n        src: item.gallery_image.url,\n        onClick: function onClick() {\n          return onOpenModalMulti(item.gallery_image.url, gallery[0].items);\n        },\n        key: item.gallery_image.url\n      })\n    );\n  }));\n};\n\nDesktopImg.propTypes = {\n  gallery: prop_types__WEBPACK_IMPORTED_MODULE_1___default.a.array,\n  onOpenModalMulti: prop_types__WEBPACK_IMPORTED_MODULE_1___default.a.func\n};\n/* harmony default export */ __webpack_exports__[\"default\"] = (DesktopImg);\n\n//# sourceURL=webpack:///./src/client/components/property/modalGallery/desktop/index.js?");

/***/ }),

/***/ "./src/client/components/property/modalGallery/desktop/styled.js":
/*!***********************************************************************!*\
  !*** ./src/client/components/property/modalGallery/desktop/styled.js ***!
  \***********************************************************************/
/*! exports provided: DesktopWrap, ImgStyle */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"DesktopWrap\", function() { return DesktopWrap; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"ImgStyle\", function() { return ImgStyle; });\n/* harmony import */ var styled_components__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! styled-components */ \"styled-components\");\n/* harmony import */ var styled_components__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(styled_components__WEBPACK_IMPORTED_MODULE_0__);\nfunction _templateObject2() {\n  var data = _taggedTemplateLiteral([\"\\n    width: \", \";\\n    height: \", \";\\n    padding-bottom: \", \";\\n    @media (min-width: 1000px) {\\n        height: \", \";\\n    }\\n    @media (min-width: 1200px) {\\n        height: \", \";\\n\\n    }\\n\"]);\n\n  _templateObject2 = function _templateObject2() {\n    return data;\n  };\n\n  return data;\n}\n\nfunction _templateObject() {\n  var data = _taggedTemplateLiteral([\"\\n  display: flex;\\n  flex-wrap: wrap;\\n  justify-content: space-between;\\n  flex-direction: row;\\n  max-width: 700px;\\n\\n  @media (min-width: 767px) {\\n      margin: auto;\\n  }\\n\\n  @media (min-width: 1000px) {\\n        display:inline-flex;\\n        flex-wrap: wrap;\\n        width:100%;\\n  }\\n    \\n\"]);\n\n  _templateObject = function _templateObject() {\n    return data;\n  };\n\n  return data;\n}\n\nfunction _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }\n\n\nvar DesktopWrap = styled_components__WEBPACK_IMPORTED_MODULE_0___default.a.section(_templateObject());\nvar ImgStyle = styled_components__WEBPACK_IMPORTED_MODULE_0___default.a.img(_templateObject2(), function (props) {\n  return props.index == 0 ? '100%' : '49%';\n}, function (props) {\n  return props.index == 0 ? '50%' : '230px';\n}, function (props) {\n  return props.index == 0 ? '0.5em' : '0.5em';\n}, function (props) {\n  return props.index == 0 ? '50%' : '175px';\n}, function (props) {\n  return props.index == 0 ? '50%' : '220px';\n});\n\n//# sourceURL=webpack:///./src/client/components/property/modalGallery/desktop/styled.js?");

/***/ })

};;